---
kind: ConfigMap
apiVersion: v1
metadata:
  name: etherpad-config
data:
  settings.json: |
    {
      "title": "UBI Etherpad",
    
      "favicon": "favicon.ico",
    
      "skinName": "colibris",
    
      "ip": "0.0.0.0",
      "port": 9001,
    
      "showSettingsInAdminPage": false,

      "suppressErrorsInPadText": true,
    
      "dbType": "dirty",
      "dbSettings": {
        "filename": "data/dirty.db"
      },
    
      "defaultPadText" : "Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at http:\/\/etherpad.org\n",
    
      "users": {
      },

      "padOptions": {
        "noColors":         false,
        "showControls":     true,
        "showChat":         true,
        "showLineNumbers":  true,
        "useMonospaceFont": false,
        "userName":         false,
        "userColor":        false,
        "rtl":              false,
        "alwaysShowChat":   false,
        "chatAndUsers":     false,
        "lang":             "en-gb"
      },
    
      "padShortcutEnabled" : {
        "altF9":     true,
        "altC":      true,
        "cmdShift2": true,
        "delete":    true,
        "return":    true,
        "esc":       true,
        "cmdS":      true,
        "tab":       true,
        "cmdZ":      true,
        "cmdY":      true,
        "cmdI":      true,
        "cmdB":      true,
        "cmdU":      true,
        "cmd5":      true,
        "cmdShiftL": true,
        "cmdShiftN": true,
        "cmdShift1": true,
        "cmdShiftC": true,
        "cmdH":      true,
        "ctrlHome":  true,
        "pageUp":    true,
        "pageDown":  true
      },
     
      "requireSession": false,
    
      "editOnly": false,
    
      "sessionNoPassword": false,
    
      "minify": true,
    
      "maxAge": 21600,
    
      "abiword": null,
    
      "soffice": null,
    
      "tidyHtml": null,
    
      "allowUnknownFileEnds": false,
    
      "requireAuthentication": false,
    
      "requireAuthorization": false,
    
      "trustProxy": false,
    
      "disableIPlogging": true,
    
      "automaticReconnectionTimeout": 0,
    
      "scrollWhenFocusLineIsOutOfViewport": {
    
        "percentage": {
          "editionAboveViewport": 0,
          "editionBelowViewport": 0
        },
    
        "duration": 0,
    
        "scrollWhenCaretIsInTheLastLineOfViewport": false,
    
        "percentageToScrollWhenUserPressesArrowUp": 0
      },

      "socketTransportProtocols" : ["xhr-polling", "jsonp-polling", "htmlfile"],
    
      "loadTest": false,
    
      "indentationOnNewLine": false,
    
      "toolbar": {
        "left": [
          ["bold", "italic", "underline", "strikethrough"],
          ["orderedlist", "unorderedlist", "indent", "outdent"],
          ["undo", "redo"],
          ["clearauthorship"]
        ],
        "right": [
          ["importexport", "timeslider", "savedrevision"],
          ["settings", "embed"],
          ["showusers"]
        ],
        "timeslider": [
          ["timeslider_export", "timeslider_returnToPad"]
        ]
      },
    
      "exposeVersion": false,
    
      "loglevel": "INFO",
    
      "logconfig" :
        { "appenders": [
            { "type": "console"
            }
          ]
        }
    }
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etherpad-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etherpad-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: etherpad
  labels:
    app.kubernetes.io/part-of: etherpad
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
        - name: etherpad
          image: 'quay.io/davivcgarcia/ubi-etherpad'
          ports:
            - containerPort: 9001
              protocol: TCP
              name: http
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - name: data
              mountPath: /opt/etherpad/data
            - name: cache
              mountPath: /opt/etherpad/node_modules
            - name: config
              mountPath: /opt/etherpad/settings.json
              subPath: settings.json
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: etherpad-data
        - name: cache
          persistentVolumeClaim:
            claimName: etherpad-cache
        - name: config
          configMap:
            name: etherpad-config
---
apiVersion: v1
kind: Service
metadata:
  name: etherpad
spec:
  selector:
    app: etherpad
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: etherpad
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: etherpad
    weight: 100
  port:
    targetPort: 9001
  wildcardPolicy: None
